---
services:
  web:
    build: .
    image: hid-tech-site:latest
    cpus: 0.3
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_SITE_URL=https://tech.hidconsult.com
    networks:
      - webnet
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:

